name: BedWars
version: 1.0
api-version: 1.21
author: deroq
main: com.github.deroq1337.bedwars.BedWars
commands:
  start:
    description: Startet vorzeitig das Spiel
  pause:
    description: Pausiert den Lobby-Countdown
  map:
    description: Verwaltet die Maps
  forcemap:
    description: Forciert eine Map